### ISSUE TITLE
BarBackgroundColor

### ISSUE THREAD

**Issue by rmenezes** [tbaggett/xfgloss#10]
Hi,

Is there any way to use Gradient Background on BarBackgroundColor (NavigationPage)?

Tks

**Comment by tbaggett** [comment]
Hello, no, the BackgroundGradient property can only be applied to the ContentPage and cell classes currently. I do have a pending enhancement request for adding support for the property to other XF classes but have been busy on other projects. Hopefully I will get to add those enhancements soon. Thanks for checking out XFGloss!
