### ISSUE TITLE
Page renderer

### ISSUE THREAD

**Issue by LuigiMaestrelli** [tbaggett/xfgloss#12]
I have a custom renderer targeting the Page on iOS.
If I add the XFGloss renderer, my renderer stop working. Looks like it isn't fired any more.

Is it normal? 
Can I use my custom renderer together with the XFGloss?

**Comment by tbaggett** [comment]
Hi Luigi,

Have you reviewed the "Using XFGloss with Other Custom XF Controls" section of the Readme.md file? (https://github.com/tbaggett/xfgloss#using-xfgloss-with-other-custom-xf-controls). 

If you followed the directions there and still see this issue, can you provide some sample code that demonstrates the issue?

Please let me know how it goes. Thanks!
