### ISSUE TITLE
Possible bug with iOS 10+

### ISSUE THREAD

**Issue by gcadmes** [tbaggett/xfgloss#14]
Hi Tom,

Firstly, fantastic control. I'm planning on using it, but wanted to run something by you before I commit.

While searching for a gradient XF control, I stumbled across the XFLabs Gradient control as well as XFGloss. I fired up the XFLabs version first and notice straight away that it's inferior (supports only two colors to XFGloss, but more importantly, with regards to iOS, I noticed that neither XFLabs or XFGloss work on an iPad Mini 4 running OS 10.2.1. (actual device, not simulator). The gradient does not show, only a white background.

Dug some more which turned up this stackoverflow post:
http://stackoverflow.com/questions/37170276/xamarin-forms-gradient-background-for-button-using-custom-renderer-with-ios

According to that post, it states, "If you are using iOS 10+ with newer version of Xamarin.Forms, the Control.Bounds during calls to LayoutSubViews will all be zeros. You will need to set the gradient layer Frame size during sets to the control's Frame property".  Follows up with a code example...

I modified the XFLabs code to match the stackoverflow code sample and it fixes the issue. Ideally I'd rather use XFGloss cause it supports Steps.

Anyway, I thought you'd like to know and possibly give this a try with a device running iOS 10+.

thoughts?

[EDIT]
Ugh! While the XFLabs was a legitimate fix, I'm embarrassed to admit, I left out the Init() in the AppDelegate when testing out XFGLoss. Please close this issue for me. 
Sorry for any confusion.

**Comment by tbaggett** [comment]
No worries! To confirm, the XFGloss background gradient rendering works correctly now that you've added the Init call? 

I committed changes to take the recommended solution into account before reading your edit. I was going to ask you to test the CI build package for me, but I can back those changes out if they're not needed.

**Comment by gcadmes** [comment]
Hi Tom,
Yes XFGloss works as expected. After adding the Init() in the AppDelegate, everything worked splendidly.

If I may ask... is this type of gradient possible using XFGloss? My UX team supplied me with this wireframe and I'm pretty darn close to re-creating it using XFGloss, but I'm not sure I can have the rotation start in the position illustrated in the attached image. 

So far using this code seems close but not quite:
`List<GradientStep> steps = new List<GradientStep>(3)
{
    new GradientStep(Color.FromHex("#AAE6FF"), 0),
    new GradientStep(Color.FromHex("#00C0EF"), .4),
    new GradientStep(Color.FromHex("#008863"), .7),
};
ContentPageGloss.SetBackgroundGradient(page, new Gradient(138, new GradientStepCollection(steps)));`

![vignette1](https://cloud.githubusercontent.com/assets/7306719/24821315/caf64a2a-1ba2-11e7-8048-642fcb1492ac.png)

thanks again for a great control!!

**Comment by tbaggett** [comment]
Cool, I'm happy to hear the current version is working correctly. I will back out the changes I committed.

The image you provided looks like it is actually 2 different gradient fills:
- A radial fill of white with approximately 60 percent opacity at its starting point on the left, down to 0 percent opacity at approximately .5 (halfway across the screen horizontally)
- A linear light blue to green fill from the top left corner to the bottom right of the image

XFGloss doesn't currently support radial fills (only linear ones) or multiple layered fills. I can add an enhancement request for this, but please be aware that I can't say when I will add enhancements. I currently only try to fix critical issues that prevent users from shipping products that depend on XFGloss.
