### ISSUE TITLE
missed .net pcl library in nuget packages >=1.1 version

### ISSUE THREAD

**Issue by rlbee** [tbaggett/xfgloss#25]
you removed pcl lib dll with .net2 standart.

**Comment by tbaggett** [comment]
fyi, I'm looking into converting to project to multi-targeting to resolve both this issue and #26. It will have to wait until this weekend for me to complete this.

**Comment by tbaggett** [comment]
Hi @rlbee, sorry it took longer than expected, but the new 1.1.3 release is now available. It supports both Net Standard 1.0 and 2.0 and should work with PCL-based projects. Can you give it a try and report back? Thanks.

**Comment by tbaggett** [comment]
Closing this issue since there were no further comments.
