### ISSUE TITLE
Why .netstandard 2.0?

### ISSUE THREAD

**Issue by napalmDaz** [tbaggett/xfgloss#26]
I use a main Core project that targets netstandard 1.4 as there is a UWP dependency that builds for Anniversary Update. Any chance of dropping the level down as I can't see any use for 2.0 in the code yet?

Thanks

**Comment by tbaggett** [comment]
I agree, I should be able to select a lower level. I will try to get that taken care of in the next day or two.

**Comment by tbaggett** [comment]
fyi, I'm looking into converting to project to multi-targeting to resolve both this issue and #25. It will have to wait until this weekend for me to complete this.

**Comment by napalmDaz** [comment]
Thanks - I've temp forked so I can carry on working and am targeting standard1.4 just fine. Multi-targetting will work great; used it elsewhere. Appreciate the update and thanks for the quick fix.

**Comment by tbaggett** [comment]
hi @napalmDaz, sorry that it took longer than I had hoped, but the new 1.1.3 release is using multitargeting and targets both Net Standard 1.0 and 2.0. Can you give it a try and report back? Thanks.

**Comment by napalmDaz** [comment]
@tbaggett Thanks for the update. I had a quick go last night and got an error at runtime regarding assembly load of v1.0.0, but that may have just been me. I have a proper go shortly. Thanks again.

**Comment by tbaggett** [comment]
Closing this issue since there has been no further comment.
