### ISSUE TITLE
Support portable-net45

### ISSUE THREAD

**Issue by jerone** [tbaggett/xfgloss#28]
The latest version removed support for `portable-net45` (`.NETPortable,Version=v4.5,Profile=Profile111`). 
I know you want to move to .netstandard, but we are currently stuck on .NET 4.5 in our portable project. 

Is there any reason to not support this anymore?

> `Could not install package 'Ansuria.XFGloss 1.1.2.89'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

**Comment by jerone** [comment]
Sorry, possible duplicate https://github.com/tbaggett/xfgloss/issues/25.

**Comment by tbaggett** [comment]
Hi @jerone, I hope to take care of that today. Converting the project to multi-targeting, which will include portable-net45.

**Comment by tbaggett** [comment]
Hello again @jerone, sorry that it took longer than expected, but the new 1.1.3 release now supports both NetStandard 1.0 and 2.0, with 1.0 offering backwards compatibility with PCL-based projects. I tested it with the 1.0.6 version of the XFGlossSample. Can you try the new release and report back? Thanks.

**Comment by tbaggett** [comment]
Closing this issue since I never received a response.
