### ISSUE TITLE
How to define as global style in App.xaml

### ISSUE THREAD

**Issue by EagleTsui** [tbaggett/xfgloss#34]
I want to each ContentPage has following element
        <xfg:ContentPageGloss.BackgroundGradient>
            <xfg:Gradient Rotation="170">
                <xfg:GradientStep StepColor="#9DCC5F" StepPercentage="0" />
                <xfg:GradientStep StepColor="#00B0CD" StepPercentage="1" />
            </xfg:Gradient>
        </xfg:ContentPageGloss.BackgroundGradient>
How can I do in App.xaml?

**Comment by tbaggett** [comment]
Sorry for the slow reply. My father was ill through most of the summer before passing away at the end of August.

You can create a named style that targets the ContentPage class as described in the Microsoft documentation [here](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/xaml/attached-properties#consuming-an-attached-property-with-a-style). I can provide an example if you have difficulty getting it working. Best of luck with it.

**Comment by EagleTsui** [comment]
Thank for reply.

Would you mind provide example in App.xaml for following style

<xfg:ContentPageGloss.BackgroundGradient>
<xfg:Gradient Rotation="170">
<xfg:GradientStep StepColor="#9DCC5F" StepPercentage="0" />
<xfg:GradientStep StepColor="#00B0CD" StepPercentage="1" />
</xfg:Gradient>
</xfg:ContentPageGloss.BackgroundGradient>
